"""S1 gate: the five app-owned stores live under ``$TDTB_HOME/state/``.

S1 moves runstate, the tag-exclusion policy, the Capacities settings, the
Capacities source record and the deferrals log out of the Obsidian vault into
the machine-local app home (``app_config.state_dir()``). The contract these
tests pin:

  - every store resolves to the new path by default;
  - a read prefers the new path and falls back READ-ONLY to the frozen vault
    copy, so S1 is reversible;
  - a write always lands at the new path and leaves every vault byte
    untouched;
  - ``TDTB_HOME`` relocates the whole state tree.

Everything here is fixture-only: ``tmp_path`` is the vault root, the autouse
``_isolated_app_home`` fixture in ``conftest.py`` points ``TDTB_HOME`` at a
private tmp dir, and no test reads or writes the operator's real vault.
"""
from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

import app_config  # noqa: E402
import capacities_builder as cb  # noqa: E402
import capacities_settings as cs  # noqa: E402
import deferrals as df  # noqa: E402
import exclusion_settings as es  # noqa: E402
import runstate  # noqa: E402


SPACE = "space-1"
TAG_A = "5a25370b-f9a0-40cf-bc3a-0cab4744913c"
DAY = date(2026, 10, 8)
PRIOR_DAY = date(2026, 10, 7)

#: The pre-S1 vault cache directory. Every legacy fixture below lives here and
#: must still be byte-identical after a write.
LEGACY_CACHE_REL = Path("00 - META/Cache")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

def _runstate_note(anchor: str, on_day: date = DAY) -> str:
    """A pre-S1 ``tdtb-runstate-<day>.md`` note (frontmatter + fenced JSON)."""
    return "\n".join([
        "---",
        f"valid_date: '{on_day}'",
        "written_at: '2026-10-07T00:00:00Z'",
        "---",
        "",
        "```json",
        json.dumps({"anchor": anchor, "eod": "11:59 PM"}),
        "```",
        "",
    ])


def _recent_selections_note(selection_id: str) -> str:
    return "\n".join([
        "---",
        "runs:",
        f"  - date: '{PRIOR_DAY}'",
        "    selections:",
        f'      - id: "{selection_id}"',
        '        path: "legacy.md"',
        "        blocks: 1",
        "---",
        "",
        "_Auto-generated by runstate.py. Do not edit manually._",
        "",
    ])


def _digest_index_payload(items: list[dict]) -> dict:
    return {"valid_date": str(DAY), "items": items}


def _exclusions_payload(revision: int, tag_id: str = TAG_A) -> dict:
    return {
        "version": 1,
        "revision": revision,
        "exclusions": {
            "tags": [{"source": "capacities", "space_id": SPACE, "tag_id": tag_id}],
        },
    }


def _capacities_settings_payload(revision: int) -> dict:
    return {
        "version": 1,
        "revision": revision,
        "native_task_auto": {
            "active_enabled": True,
            "due_enabled": True,
            "deadline_enabled": True,
            "deadline_horizon_days": 2,
        },
        "excluded": {},
        "active_structures": {},
    }


def _capacities_source_payload(revision: int) -> dict:
    return {
        "version": 1,
        "revision": revision,
        "space_id": SPACE,
        "structures": [{"structure_id": "RootTask"}],
    }


def _deferrals_payload(items: dict) -> dict:
    return {"version": 1, "items": items}


def _deferral_entry(count: int = 2, todoist_id: str = "42") -> dict:
    return {
        "count": count,
        "last_deferred": str(PRIOR_DAY),
        "name": "Legacy",
        "path": "",
        "todoist_id": todoist_id,
    }


#: Legacy vault file name -> bytes written by :func:`_seed_legacy_vault`. Every
#: one of the five stores is represented, plus the two runtime lock artifacts
#: that must never be migrated.
def _legacy_files(tag_id: str = TAG_A) -> dict[str, str]:
    return {
        f"tdtb-runstate-{DAY}.md": _runstate_note("legacy-anchor"),
        "tdtb-recent-selections.md": _recent_selections_note("legacy-1"),
        f"tdtb-digest-index-{DAY}.json": json.dumps(
            _digest_index_payload([{"name": "Legacy", "todoist_id": "", "path": "legacy.md"}])
        ),
        "tdtb-exclusion-settings.json": json.dumps(_exclusions_payload(3, tag_id)),
        "tdtb-capacities-settings.json": json.dumps(_capacities_settings_payload(5)),
        "tdtb-capacities-source.json": json.dumps(_capacities_source_payload(2)),
        "tdtb-deferrals.json": json.dumps(
            _deferrals_payload({"todoist:42": _deferral_entry()})
        ),
        "tdtb-exclusion-settings.lock": "",
        "tdtb-capacities-settings.lock": "",
        "tdtb-capacities-source.lock": "",
    }


def _seed_legacy_vault(vault: Path, tag_id: str = TAG_A) -> dict[str, bytes]:
    """Write the pre-S1 vault cache. Returns name -> bytes for later comparison."""
    cache = vault / LEGACY_CACHE_REL
    cache.mkdir(parents=True, exist_ok=True)
    written: dict[str, bytes] = {}
    for name, text in _legacy_files(tag_id).items():
        target = cache / name
        target.write_text(text, encoding="utf-8")
        written[name] = target.read_bytes()
    return written


def _snapshot(root: Path) -> dict[str, bytes]:
    """Every file under ``root`` as relpath -> bytes (the "nothing changed" probe)."""
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


@pytest.fixture
def vault(tmp_path: Path) -> Path:
    root = tmp_path / "vault-root"
    root.mkdir()
    return root


@pytest.fixture
def legacy(vault: Path) -> dict[str, bytes]:
    return _seed_legacy_vault(vault)


# ---------------------------------------------------------------------------
# 1. Every store resolves under the state dir
# ---------------------------------------------------------------------------

def test_every_store_path_is_under_the_state_dir(tmp_path: Path, monkeypatch) -> None:
    home = tmp_path / "home"
    monkeypatch.setenv("TDTB_HOME", str(home))
    state = home / "state"

    assert app_config.state_dir() == state
    assert runstate.state_runstate_dir() == state / "runstate"
    assert runstate.state_runstate_path(DAY) == state / "runstate" / f"tdtb-runstate-{DAY}.md"
    assert (
        runstate.state_recent_selections_path()
        == state / "runstate" / "tdtb-recent-selections.md"
    )
    assert (
        runstate.state_digest_index_path(DAY)
        == state / "runstate" / f"tdtb-digest-index-{DAY}.json"
    )
    assert es.settings_path() == state / "exclusions.json"
    assert cs.settings_path() == state / "capacities-settings.json"
    assert cb.source_path() == state / "capacities-source.json"
    assert df.deferrals_path() == state / "deferrals.json"

    # Locks are runtime artifacts at the new location, never in the vault.
    assert es.lock_path() == state / "exclusions.lock"
    assert cs.lock_path() == state / "capacities-settings.lock"
    assert cb.lock_path() == state / "capacities-source.lock"

    for path in (
        runstate.state_runstate_path(DAY),
        es.settings_path(),
        cs.settings_path(),
        cb.source_path(),
        df.deferrals_path(),
    ):
        assert path.is_relative_to(state)


def test_resolving_a_path_creates_nothing(vault: Path) -> None:
    assert not es.settings_path().exists()
    assert not cs.settings_path().exists()
    assert not cb.source_path().exists()
    assert not df.deferrals_path().exists()
    assert not runstate.state_runstate_dir().exists()
    assert _snapshot(vault) == {}


# ---------------------------------------------------------------------------
# 2 + 3. Reads: new path first, vault fallback (read-only)
# ---------------------------------------------------------------------------

def test_all_stores_read_the_legacy_vault_with_no_state_files(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    assert runstate.read_runstate(vault, DAY) == {"anchor": "legacy-anchor", "eod": "11:59 PM"}
    assert runstate.read_recent_selections(vault)[0]["selections"][0]["id"] == "legacy-1"
    assert runstate.read_digest_index(vault, DAY)[0]["name"] == "Legacy"
    assert es.read_settings(vault).settings.revision == 3
    assert cs.read_settings(vault).settings.revision == 5
    assert cb.read_source(vault).revision == 2
    assert df.load_deferrals(vault)["todoist:42"]["count"] == 2

    # A fallback read is read-only: the vault snapshot is untouched.
    assert _snapshot(vault)[str(LEGACY_CACHE_REL / "tdtb-runstate-2026-10-08.md")] == (
        legacy["tdtb-runstate-2026-10-08.md"]
    )


def test_all_stores_prefer_the_state_copy_when_both_exist(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    runstate.state_runstate_path(DAY).parent.mkdir(parents=True, exist_ok=True)
    runstate.state_runstate_path(DAY).write_text(_runstate_note("state-anchor"), encoding="utf-8")
    runstate.state_recent_selections_path().write_text(
        _recent_selections_note("state-1"), encoding="utf-8"
    )
    runstate.state_digest_index_path(DAY).write_text(
        json.dumps(_digest_index_payload([{"name": "State"}])), encoding="utf-8"
    )
    es.settings_path().parent.mkdir(parents=True, exist_ok=True)
    es.settings_path().write_text(
        json.dumps(_exclusions_payload(9, TAG_A)), encoding="utf-8"
    )
    cs.settings_path().write_text(json.dumps(_capacities_settings_payload(11)), encoding="utf-8")
    cb.source_path().write_text(json.dumps(_capacities_source_payload(13)), encoding="utf-8")
    df.deferrals_path().write_text(
        json.dumps(_deferrals_payload({"todoist:99": _deferral_entry(7, "99")})),
        encoding="utf-8",
    )

    assert runstate.read_runstate(vault, DAY)["anchor"] == "state-anchor"
    assert runstate.read_recent_selections(vault)[0]["selections"][0]["id"] == "state-1"
    assert runstate.read_digest_index(vault, DAY)[0]["name"] == "State"
    assert es.read_settings(vault).settings.revision == 9
    assert cs.read_settings(vault).settings.revision == 11
    assert cb.read_source(vault).revision == 13
    assert df.load_deferrals(vault)["todoist:99"]["count"] == 7

    # The vault copies are still exactly the pre-S1 bytes.
    cache = vault / LEGACY_CACHE_REL
    for name, raw in legacy.items():
        assert (cache / name).read_bytes() == raw


def test_legacy_and_state_path_helpers_point_at_different_files(vault: Path) -> None:
    assert es.legacy_settings_path(vault) == vault / LEGACY_CACHE_REL / "tdtb-exclusion-settings.json"
    assert cs.legacy_settings_path(vault) == vault / LEGACY_CACHE_REL / "tdtb-capacities-settings.json"
    assert cb.legacy_source_path(vault) == vault / LEGACY_CACHE_REL / "tdtb-capacities-source.json"
    assert df.legacy_deferrals_path(vault) == vault / LEGACY_CACHE_REL / "tdtb-deferrals.json"
    assert (
        runstate.legacy_runstate_path(vault, DAY)
        == vault / LEGACY_CACHE_REL / f"tdtb-runstate-{DAY}.md"
    )


# ---------------------------------------------------------------------------
# 4. Writes land at the new path; the vault copy is untouched
# ---------------------------------------------------------------------------

def test_runstate_write_lands_in_state_and_leaves_the_vault_untouched(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)
    written = runstate.write_runstate(
        vault, DAY, {**runstate.build_runstate(), "anchor": "state-anchor"}
    )

    assert written == runstate.state_runstate_path(DAY)
    assert written.is_file()
    assert runstate.read_runstate(vault, DAY)["anchor"] == "state-anchor"
    assert _snapshot(vault) == before
    # The frozen vault note still holds the pre-S1 value.
    assert (
        vault / LEGACY_CACHE_REL / f"tdtb-runstate-{DAY}.md"
    ).read_bytes() == legacy[f"tdtb-runstate-{DAY}.md"]


def test_runstate_cleanup_never_deletes_a_vault_note(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    """Trigger-1 cleanup prunes earlier-dated notes in the ACTIVE directory
    only — the frozen vault history is the rollback point."""
    stale = vault / LEGACY_CACHE_REL / "tdtb-runstate-2026-10-01.md"
    stale.write_text(_runstate_note("older", date(2026, 10, 1)), encoding="utf-8")
    before = _snapshot(vault)

    runstate.write_runstate(vault, DAY, runstate.build_runstate())

    assert stale.read_bytes() == before[str(LEGACY_CACHE_REL / stale.name)]
    assert _snapshot(vault) == before


def test_recent_selections_write_lands_in_state_and_keeps_the_vault_copy(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)

    written = runstate.append_recent_selection(
        vault, DAY, [{"id": "state-1", "path": "state.md", "blocks": 2}]
    )

    assert written == runstate.state_recent_selections_path()
    runs = runstate.read_recent_selections(vault)
    assert runs[0]["selections"][0]["id"] == "state-1"
    # The prior vault run is carried forward, not lost.
    assert runs[1]["selections"][0]["id"] == "legacy-1"
    assert _snapshot(vault) == before


def test_digest_index_write_lands_in_state_and_keeps_the_vault_copy(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)

    written = runstate.write_digest_index(
        vault, DAY, [{"name": "State", "todoist_id": "1", "path": "state.md"}]
    )

    assert written == runstate.state_digest_index_path(DAY)
    assert [i["name"] for i in runstate.read_digest_index(vault, DAY)] == ["State"]
    assert _snapshot(vault) == before


def test_exclusions_write_lands_in_state_and_keeps_the_vault_copy(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)

    saved = es.save_settings(
        vault,
        expected_revision=3,
        exclusions=[es.TagExclusion(source="capacities", space_id=SPACE, tag_id=TAG_A)],
    )

    assert saved.revision == 4
    assert es.settings_path().is_file()
    assert es.read_settings(vault).settings.revision == 4
    assert es.lock_path().is_file()
    # The vault's own 0-byte lock artifact is left exactly as it was.
    assert (
        vault / LEGACY_CACHE_REL / "tdtb-exclusion-settings.lock"
    ).read_bytes() == legacy["tdtb-exclusion-settings.lock"]
    assert _snapshot(vault) == before


def test_capacities_settings_write_lands_in_state_and_keeps_the_vault_copy(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)

    saved = cs.save_settings(
        vault,
        expected_revision=5,
        native_task_auto=cs.NativeTaskAutoPolicy(),
    )

    assert saved.revision == 6
    assert cs.settings_path().is_file()
    assert cs.read_settings(vault).settings.revision == 6
    assert _snapshot(vault) == before


def test_capacities_source_write_lands_in_state_and_keeps_the_vault_copy(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)

    saved = cb.save_source(
        vault,
        expected_revision=2,
        space_id=SPACE,
        structures=[cb.SourceStructureRecord(structure_id="custom-project")],
    )

    assert saved.revision == 3
    assert cb.source_path().is_file()
    assert cb.read_source(vault).revision == 3
    assert _snapshot(vault) == before


def test_deferrals_write_lands_in_state_and_keeps_the_vault_copy(
    vault: Path, legacy: dict[str, bytes]
) -> None:
    before = _snapshot(vault)

    df.record_deferral(vault, {"name": "Fresh", "todoist_id": "99"}, DAY)

    assert df.deferrals_path().is_file()
    items = df.load_deferrals(vault)
    assert items["todoist:99"]["count"] == 1
    # The vault entry is carried forward into the state copy.
    assert items["todoist:42"]["count"] == 2
    assert _snapshot(vault) == before


# ---------------------------------------------------------------------------
# 6. TDTB_HOME relocates the whole state tree
# ---------------------------------------------------------------------------

def test_tdtb_home_moves_every_store(
    vault: Path, legacy: dict[str, bytes], tmp_path: Path, monkeypatch
) -> None:
    home_a = tmp_path / "home-a"
    home_b = tmp_path / "home-b"

    monkeypatch.setenv("TDTB_HOME", str(home_a))
    runstate.write_runstate(vault, DAY, {**runstate.build_runstate(), "anchor": "a"})
    es.save_settings(
        vault,
        expected_revision=3,
        exclusions=[es.TagExclusion(source="capacities", space_id=SPACE, tag_id=TAG_A)],
    )
    cs.save_settings(vault, expected_revision=5, native_task_auto=cs.NativeTaskAutoPolicy())
    cb.save_source(
        vault,
        expected_revision=2,
        space_id=SPACE,
        structures=[cb.SourceStructureRecord(structure_id="custom-project")],
    )
    df.record_deferral(vault, {"name": "Fresh", "todoist_id": "99"}, DAY)

    for path in (
        runstate.state_runstate_path(DAY),
        es.settings_path(),
        cs.settings_path(),
        cb.source_path(),
        df.deferrals_path(),
    ):
        assert path.is_relative_to(home_a / "state")
        assert path.is_file()

    # A different home sees none of it and falls back to the frozen vault.
    monkeypatch.setenv("TDTB_HOME", str(home_b))
    assert runstate.read_runstate(vault, DAY)["anchor"] == "legacy-anchor"
    assert es.read_settings(vault).settings.revision == 3
    assert cs.read_settings(vault).settings.revision == 5
    assert cb.read_source(vault).revision == 2
    assert df.load_deferrals(vault)["todoist:42"]["count"] == 2
    assert not (home_b / "state").exists()


def test_config_json_and_state_share_one_home(
    tmp_path: Path, monkeypatch
) -> None:
    home = tmp_path / "custom"
    monkeypatch.setenv("TDTB_HOME", str(home))
    assert app_config.config_path() == home / "config.json"
    assert es.settings_path().parent == app_config.state_dir()
